module.exports = (sequelize, DataTypes) => sequelize.define('FinanceiroDdaBoleto', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  provider: { type: DataTypes.STRING(30), allowNull: false, defaultValue: 'BB' },
  provider_document_id: { type: DataTypes.STRING(160), allowNull: false },
  empresa_id: { type: DataTypes.INTEGER, allowNull: true },
  payment_account_id: { type: DataTypes.INTEGER, allowNull: true },
  sincronizacao_id: { type: DataTypes.BIGINT, allowNull: true },
  beneficiario_nome: { type: DataTypes.STRING(255), allowNull: true },
  beneficiario_documento: { type: DataTypes.STRING(20), allowNull: true },
  pagador_nome: { type: DataTypes.STRING(255), allowNull: true },
  pagador_documento: { type: DataTypes.STRING(20), allowNull: true },
  banco_codigo: { type: DataTypes.STRING(10), allowNull: true },
  banco_nome: { type: DataTypes.STRING(120), allowNull: true },
  nosso_numero: { type: DataTypes.STRING(120), allowNull: true },
  linha_digitavel: { type: DataTypes.STRING(255), allowNull: true },
  codigo_barras: { type: DataTypes.STRING(255), allowNull: true },
  data_emissao: { type: DataTypes.DATEONLY, allowNull: true },
  data_vencimento: { type: DataTypes.DATEONLY, allowNull: false },
  valor_original: { type: DataTypes.DECIMAL(16, 2), allowNull: false },
  valor_atual: { type: DataTypes.DECIMAL(16, 2), allowNull: false },
  provider_status: { type: DataTypes.STRING(60), allowNull: true },
  status: { type: DataTypes.STRING(30), allowNull: false, defaultValue: 'NOVO' },
  titulo_sugerido_id: { type: DataTypes.INTEGER, allowNull: true },
  titulo_financeiro_id: { type: DataTypes.INTEGER, allowNull: true },
  fingerprint: { type: DataTypes.STRING(64), allowNull: false },
  payload_hash: { type: DataTypes.STRING(64), allowNull: false },
  raw_payload_json: { type: DataTypes.TEXT('long'), allowNull: true },
  primeira_consulta_em: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
  ultima_consulta_em: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
  vinculado_em: { type: DataTypes.DATE, allowNull: true },
  vinculado_por: { type: DataTypes.INTEGER, allowNull: true },
  ignorado_em: { type: DataTypes.DATE, allowNull: true },
  ignorado_por: { type: DataTypes.INTEGER, allowNull: true },
  ignorado_motivo: { type: DataTypes.STRING(500), allowNull: true }
}, { tableName: 'financeiro_dda_boletos', timestamps: true });
