'use strict';

const SST_EVENT_SEVERITY = {
  INFO: 'INFO',
  ALERTA: 'ALERTA',
  CRITICA: 'CRITICA'
};

const SST_EVENT_CATALOG = {
  SST_ASO_CADASTRADO: { severity: SST_EVENT_SEVERITY.INFO, domain: 'ASO' },
  SST_ASO_VENCENDO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'ASO' },
  SST_ASO_VENCIDO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'ASO' },
  SST_COLABORADOR_INAPTO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'ASO' },
  SST_EXAME_VENCENDO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'EXAMES' },
  SST_EXAME_VENCIDO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'EXAMES' },
  SST_EPI_ENTREGUE: { severity: SST_EVENT_SEVERITY.INFO, domain: 'EPI' },
  SST_EPI_VENCENDO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'EPI' },
  SST_EPI_VENCIDO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'EPI' },
  SST_COLABORADOR_SEM_EPI: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'EPI' },
  SST_TREINAMENTO_VENCENDO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'TREINAMENTOS' },
  SST_TREINAMENTO_VENCIDO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'TREINAMENTOS' },
  SST_COLABORADOR_SEM_NR: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'TREINAMENTOS' },
  SST_ACIDENTE_REGISTRADO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'ACIDENTES' },
  SST_ACIDENTE_GRAVE: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'ACIDENTES' },
  SST_RISCO_CRITICO_IDENTIFICADO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'RISCOS' },
  SST_EVENTO_ESOCIAL_REJEITADO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'ESOCIAL' },
  SST_DOCUMENTO_EXPIRADO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'DOCUMENTOS' },
  SST_DOCUMENTO_VENCENDO: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'DOCUMENTOS' },
  SST_FUNCAO_ALTERADA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'RH' },
  SST_OBRA_ALTERADA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'RH' },
  SST_ADMISSAO_DETECTADA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'RH' },
  SST_DESLIGAMENTO_DETECTADO: { severity: SST_EVENT_SEVERITY.INFO, domain: 'RH' },
  SST_REVISAO_CONFORMIDADE_OBRIGATORIA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'CONFORMIDADE' },
  SST_PENDENCIA_OPERACIONAL_GERADA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'PENDENCIAS' },
  SST_BLOQUEIO_OPERACIONAL_GERADO: { severity: SST_EVENT_SEVERITY.CRITICA, domain: 'BLOQUEIOS' },
  SST_NOTIFICACAO_GERADA: { severity: SST_EVENT_SEVERITY.INFO, domain: 'NOTIFICACOES' },
  SST_WORKFLOW_EXECUTADO: { severity: SST_EVENT_SEVERITY.INFO, domain: 'WORKFLOW' },
  SST_WORKFLOW_ACAO_EXECUTADA: { severity: SST_EVENT_SEVERITY.INFO, domain: 'WORKFLOW' },
  SST_AUTOMACAO_EXECUTADA: { severity: SST_EVENT_SEVERITY.INFO, domain: 'AUTOMACAO' },
  SST_RECOMENDACAO_GERADA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'RECOMENDACOES' },
  SST_DOCUMENTO_ANALISADO_IA: { severity: SST_EVENT_SEVERITY.ALERTA, domain: 'IA_DOCUMENTAL' }
};

function getEventDefinition(type) {
  return SST_EVENT_CATALOG[type] || { severity: SST_EVENT_SEVERITY.INFO, domain: 'SST' };
}

module.exports = {
  SST_EVENT_CATALOG,
  SST_EVENT_SEVERITY,
  getEventDefinition
};
