const CLASSIFICACOES_GERENCIAIS_FINANCEIRAS = [
  'OPERACIONAL',
  'ENDIVIDAMENTO',
  'INVESTIMENTO',
  'PATRIMONIAL',
  'INTERCOMPANY',
  'TRANSFERENCIA_INTERNA',
  'IMPOSTO',
  'FOLHA',
  'OUTROS'
];

const CLASSIFICACOES_GERENCIAIS_LABELS = {
  OPERACIONAL: 'Operacional',
  ENDIVIDAMENTO: 'Endividamento',
  INVESTIMENTO: 'Investimento',
  PATRIMONIAL: 'Patrimonial',
  INTERCOMPANY: 'Intercompany',
  TRANSFERENCIA_INTERNA: 'Transferencia interna',
  IMPOSTO: 'Imposto',
  FOLHA: 'Folha',
  OUTROS: 'Outros'
};

module.exports = {
  CLASSIFICACOES_GERENCIAIS_FINANCEIRAS,
  CLASSIFICACOES_GERENCIAIS_LABELS
};
