const TIPO_EMPRESA_HOLDING = 'HOLDING';
const TIPO_EMPRESA_OPERACIONAL = 'OPERACIONAL';

const TIPOS_EMPRESA_GRUPO = [
  TIPO_EMPRESA_HOLDING,
  TIPO_EMPRESA_OPERACIONAL
];

const TIPO_GERENCIAL_HOLDING = 'HOLDING';
const TIPO_GERENCIAL_TESOURARIA = 'TESOURARIA';
const TIPO_GERENCIAL_SPE = 'SPE';
const TIPO_GERENCIAL_ADMINISTRATIVA = 'ADMINISTRATIVA';
const TIPO_GERENCIAL_OPERACIONAL = 'OPERACIONAL';
const TIPO_GERENCIAL_PATRIMONIAL = 'PATRIMONIAL';
const TIPO_GERENCIAL_COMERCIAL = 'COMERCIAL';
const TIPO_GERENCIAL_RH_FOLHA = 'RH_FOLHA';
const TIPO_GERENCIAL_INVESTIMENTOS = 'INVESTIMENTOS';

const TIPOS_GERENCIAIS_EMPRESA_GRUPO = [
  TIPO_GERENCIAL_HOLDING,
  TIPO_GERENCIAL_TESOURARIA,
  TIPO_GERENCIAL_SPE,
  TIPO_GERENCIAL_ADMINISTRATIVA,
  TIPO_GERENCIAL_OPERACIONAL,
  TIPO_GERENCIAL_PATRIMONIAL,
  TIPO_GERENCIAL_COMERCIAL,
  TIPO_GERENCIAL_RH_FOLHA,
  TIPO_GERENCIAL_INVESTIMENTOS
];

function normalizeTipoEmpresaGrupo(value) {
  const normalized = String(value || TIPO_EMPRESA_OPERACIONAL).trim().toUpperCase();
  return TIPOS_EMPRESA_GRUPO.includes(normalized)
    ? normalized
    : TIPO_EMPRESA_OPERACIONAL;
}

function normalizeTipoGerencialEmpresaGrupo(value) {
  const normalized = String(value || TIPO_GERENCIAL_OPERACIONAL).trim().toUpperCase();
  return TIPOS_GERENCIAIS_EMPRESA_GRUPO.includes(normalized)
    ? normalized
    : TIPO_GERENCIAL_OPERACIONAL;
}

module.exports = {
  TIPO_EMPRESA_HOLDING,
  TIPO_EMPRESA_OPERACIONAL,
  TIPOS_EMPRESA_GRUPO,
  TIPO_GERENCIAL_HOLDING,
  TIPO_GERENCIAL_TESOURARIA,
  TIPO_GERENCIAL_SPE,
  TIPO_GERENCIAL_ADMINISTRATIVA,
  TIPO_GERENCIAL_OPERACIONAL,
  TIPO_GERENCIAL_PATRIMONIAL,
  TIPO_GERENCIAL_COMERCIAL,
  TIPO_GERENCIAL_RH_FOLHA,
  TIPO_GERENCIAL_INVESTIMENTOS,
  TIPOS_GERENCIAIS_EMPRESA_GRUPO,
  normalizeTipoEmpresaGrupo,
  normalizeTipoGerencialEmpresaGrupo
};
