const TIPO_INTERCOMPANY_APORTE = 'APORTE';
const TIPO_INTERCOMPANY_EMPRESTIMO = 'EMPRESTIMO';
const TIPO_INTERCOMPANY_REEMBOLSO = 'REEMBOLSO';
const TIPO_INTERCOMPANY_RATEIO = 'RATEIO';
const TIPO_INTERCOMPANY_COBERTURA_CAIXA = 'COBERTURA_CAIXA';
const TIPO_INTERCOMPANY_FOLHA = 'FOLHA';
const TIPO_INTERCOMPANY_ADMINISTRATIVO = 'ADMINISTRATIVO';
const TIPO_INTERCOMPANY_IMPOSTO = 'IMPOSTO';
const TIPO_INTERCOMPANY_TRANSFERENCIA_OPERACIONAL = 'TRANSFERENCIA_OPERACIONAL';

const TIPOS_INTERCOMPANY = [
  TIPO_INTERCOMPANY_APORTE,
  TIPO_INTERCOMPANY_EMPRESTIMO,
  TIPO_INTERCOMPANY_REEMBOLSO,
  TIPO_INTERCOMPANY_RATEIO,
  TIPO_INTERCOMPANY_COBERTURA_CAIXA,
  TIPO_INTERCOMPANY_FOLHA,
  TIPO_INTERCOMPANY_ADMINISTRATIVO,
  TIPO_INTERCOMPANY_IMPOSTO,
  TIPO_INTERCOMPANY_TRANSFERENCIA_OPERACIONAL
];

function normalizeTipoIntercompany(value) {
  const normalized = String(value || '').trim().toUpperCase();
  return TIPOS_INTERCOMPANY.includes(normalized) ? normalized : null;
}

module.exports = {
  TIPO_INTERCOMPANY_APORTE,
  TIPO_INTERCOMPANY_EMPRESTIMO,
  TIPO_INTERCOMPANY_REEMBOLSO,
  TIPO_INTERCOMPANY_RATEIO,
  TIPO_INTERCOMPANY_COBERTURA_CAIXA,
  TIPO_INTERCOMPANY_FOLHA,
  TIPO_INTERCOMPANY_ADMINISTRATIVO,
  TIPO_INTERCOMPANY_IMPOSTO,
  TIPO_INTERCOMPANY_TRANSFERENCIA_OPERACIONAL,
  TIPOS_INTERCOMPANY,
  normalizeTipoIntercompany
};
